=== calderin21/xml_pruebas/alumnos.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="alumnos">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="alumno" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="nombre" type="NombreTipo"/>
              <xs:element name="apellido" type="NombreTipo"/>
              <xs:element name="curso" type="xs:string"/>
              <xs:element name="nota_media" type="NotaTipo"/>
            </xs:sequence>
                     <xs:attribute name="num_exp" type="ExpedienteTipo" use="required"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <!-- Tipos personalizados -->
  <xs:simpleType name="ExpedienteTipo">
    <xs:restriction base="xs:string">
      <xs:pattern value="[A-Z][0-9]{3}"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="NombreTipo">
    <xs:restriction base="xs:string">
      <xs:pattern value="[A-Za-zÁÉÍÓÚáéíóúÑñ ]+"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="NotaTipo">
    <xs:restriction base="xs:integer">
      <xs:minInclusive value="1"/>
      <xs:maxInclusive value="10"/>
    </xs:restriction>
  </xs:simpleType>

</xs:schema>

=== calderin21/xml_pruebas/alumnos.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="alumnos.xsl"?>
<alumnos xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="alumnos.xsd">
    <alumno num_exp="A001" >
        <nombre>Constantino</nombre>
        <apellido>Lantigua Calderín</apellido>
        <curso>2º ESO</curso>
        <nota_media>7</nota_media>
    </alumno>
    <alumno num_exp="A002" >
        <nombre>Jose</nombre>
        <apellido>Cruz Caballero</apellido>
        <curso>2º ESO</curso>
        <nota_media>10</nota_media>
    </alumno>
    <alumno num_exp="B003" >
        <nombre>Pepe</nombre>
        <apellido>Cruz</apellido>
        <curso>2º ESO</curso>
        <nota_media>10</nota_media>
    </alumno>
</alumnos>
